package report

import (
	"fmt"
	"io"
	"strings"

	"github.com/DevShedLabs/devscan/internal/schema"
)

func renderMarkdown(w io.Writer, r *schema.Report) error {
	p := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("# DevScan Report")
	p("")
	p("**Generated:** %s  ", r.Meta.Timestamp.Format("2006-01-02 15:04:05 MST"))
	p("**Target:** %s  ", r.Meta.Target)
	if r.Meta.Path != "" {
		p("**Path:** `%s`  ", r.Meta.Path)
	}
	p("**Scan duration:** %s  ", formatDuration(r.Meta.DurationMs))
	if r.Meta.OS != "" {
		osLine := r.Meta.OS
		if r.Meta.OSVersion != "" {
			osLine += " " + r.Meta.OSVersion
		}
		p("**OS:** %s  ", osLine)
	}
	if r.Meta.Chip != "" {
		p("**Chip:** %s  ", r.Meta.Chip)
	}
	if r.Meta.Arch != "" {
		p("**Arch:** %s  ", r.Meta.Arch)
	}
	p("")

	// Summary
	p("## Summary")
	p("")
	p("| | |")
	p("|---|---|")
	p("| Runtimes detected | %d |", r.Summary.Runtimes)
	p("| Packages scanned | %d |", r.Summary.Packages)
	p("| Critical vulnerabilities | %d |", r.Summary.Vulnerabilities.Critical)
	p("| High vulnerabilities | %d |", r.Summary.Vulnerabilities.High)
	p("| Medium vulnerabilities | %d |", r.Summary.Vulnerabilities.Medium)
	p("| Low vulnerabilities | %d |", r.Summary.Vulnerabilities.Low)
	p("| Scan duration | %s |", formatDuration(r.Meta.DurationMs))
	p("")

	// Runtimes
	p("## Runtimes")
	p("")
	if len(r.Runtimes) == 0 {
		p("No runtimes detected.")
	} else {
		p("| Runtime | Version | Status | Path |")
		p("|---|---|---|---|")
		for _, rt := range r.Runtimes {
			status := string(rt.Status)
			if rt.Latest != "" && rt.Status == schema.StatusOutdated {
				status = fmt.Sprintf("outdated (latest: %s)", rt.Latest)
			}
			p("| %s | `%s` | %s | `%s` |", rt.Name, rt.Version, status, rt.Path)
		}
	}
	p("")

	// Vulnerabilities
	vs := r.Summary.Vulnerabilities
	vulnTotal := vs.Critical + vs.High + vs.Medium + vs.Low
	p("## Vulnerabilities (%d total)", vulnTotal)
	p("")
	if len(r.Vulnerabilities) == 0 {
		p("No vulnerabilities found.")
	} else {
		groups := groupBySeverity(r.Vulnerabilities)
		for _, sev := range []schema.Severity{
			schema.SeverityCritical,
			schema.SeverityHigh,
			schema.SeverityMedium,
			schema.SeverityLow,
			schema.SeverityUnknown,
		} {
			vulns, ok := groups[sev]
			if !ok || len(vulns) == 0 {
				continue
			}
			p("### %s", severityHeading(sev))
			p("")
			for _, pkg := range vulns {
				p("#### `%s@%s` — %s", pkg.name, pkg.version, pkg.ecosystem)
				p("")
				for _, path := range pkg.paths {
					p("**Path:** `%s`  ", path)
				}
				p("")
				hasFixed := anyFixedIn(pkg.vulns)
				hasFix := anyFix(pkg.vulns)
				header := "| Advisory | Title"
				sep := "|---|---"
				if hasFixed {
					header += " | Fixed In"
					sep += "|---"
				}
				if hasFix {
					header += " | Fix"
					sep += "|---"
				}
				p(header + " |")
				p(sep + "|")
				for _, v := range pkg.vulns {
					title := v.Title
					if title == "" {
						title = v.ID
					}
					row := fmt.Sprintf("| [%s](https://osv.dev/vulnerability/%s) | %s",
						v.ID, v.ID, title)
					if hasFixed {
						fixedIn := v.FixedIn
						if fixedIn == "" {
							fixedIn = "—"
						}
						row += " | " + fixedIn
					}
					if hasFix {
						fix := "—"
						if v.Fix != nil && v.Fix.Command != "" {
							fix = "`" + v.Fix.Command + "`"
						}
						row += " | " + fix
					}
					p(row + " |")
				}
				p("")
			}
		}
	}

	// Packages
	p("## Installed Packages")
	p("")
	p("| Package | Version | Ecosystem | Path |")
	p("|---|---|---|---|")
	for _, pkg := range r.Packages {
		path := pkg.Path
		if path == "" {
			path = "—"
		}
		p("| %s | `%s` | %s | `%s` |", pkg.Name, pkg.Version, pkg.Ecosystem, path)
	}
	p("")

	p("---")
	p("*Generated by [devscan](https://github.com/DevShedLabs/devscan)*")

	return nil
}

type pkgGroup struct {
	name      string
	version   string
	ecosystem string
	paths     []string
	vulns     []schema.Vulnerability
}

func groupBySeverity(vulns []schema.Vulnerability) map[schema.Severity][]pkgGroup {
	type key struct{ eco, name, version string }
	order := []key{}
	groups := map[key]*pkgGroup{}

	for _, v := range vulns {
		k := key{v.Ecosystem, v.Package, v.InstalledVersion}
		if _, exists := groups[k]; !exists {
			order = append(order, k)
			groups[k] = &pkgGroup{
				name:      v.Package,
				version:   v.InstalledVersion,
				ecosystem: v.Ecosystem,
				paths:     v.Paths,
			}
		}
		groups[k].vulns = append(groups[k].vulns, v)
	}

	// Index package paths
	// (path is on the Vulnerability's package — we surface it via the vuln list)

	// Bucket by worst severity
	result := map[schema.Severity][]pkgGroup{}
	rank := map[schema.Severity]int{
		schema.SeverityCritical: 4,
		schema.SeverityHigh:     3,
		schema.SeverityMedium:   2,
		schema.SeverityLow:      1,
		schema.SeverityUnknown:  0,
	}

	for _, k := range order {
		g := groups[k]
		worst := schema.SeverityUnknown
		for _, v := range g.vulns {
			if rank[v.Severity] > rank[worst] {
				worst = v.Severity
			}
		}
		result[worst] = append(result[worst], *g)
	}

	return result
}

func severityHeading(s schema.Severity) string {
	switch s {
	case schema.SeverityCritical:
		return "🔴 Critical"
	case schema.SeverityHigh:
		return "🟠 High"
	case schema.SeverityMedium:
		return "🟡 Medium"
	case schema.SeverityLow:
		return "🟢 Low"
	default:
		return "⚪ Unknown Severity"
	}
}

func severityBadge(s schema.Severity) string {
	switch s {
	case schema.SeverityCritical:
		return "🔴 Critical"
	case schema.SeverityHigh:
		return "🟠 High"
	case schema.SeverityMedium:
		return "🟡 Medium"
	case schema.SeverityLow:
		return "🟢 Low"
	default:
		return "⚪ Unknown"
	}
}

func joinStrings(ss []string, sep string) string {
	return strings.Join(ss, sep)
}

